# DEVILSEC · picom · performance preset
# No blur, no fade, no animations. For VMs / low-spec hosts.

backend = "xrender"
vsync = true
use-damage = true

shadow = false;
fading = false;
inactive-opacity = 1.0;
frame-opacity = 1.0;
corner-radius = 0;

blur-background = false;

wintypes:
{
    normal     = { shadow = false; fade = false; };
    tooltip    = { shadow = false; fade = false; };
    dock       = { shadow = false; };
    dnd        = { shadow = false; };
};
